service: calendar-sync

provider:
  name: aws
  runtime: java8
  region: ap-northeast-1

package:
  artifact: target/scala-2.12/calendar_sync.jar

functions:
  calendar_sync:
    handler: calendar_sync.Handler

